port: 7974
host: http://127.0.0.1:7974
concurrent: 2
database: mongodb://127.0.0.1:27017/doj
log: debug
secret: doj_secret
registration: true
mail:
  host: smtp.mailtrap.io
  port: 2525
  auth:
    user: 2e35494e193977
    pass: 1a2a2128eb634e
languages:
- name: C
  suffix: c
  source: main.c
  compile:
    time: 10.0
    cmd: /usr/bin/gcc
    args: [ main.c, -o, main, -O2, -lm, -std=c99, -DONLINE_JUDGE ]
  run:
    ratio: 1.0
    cmd: main
- name: C++
  suffix: cpp
  source: main.cpp
  compile:
    time: 10.0
    cmd: /usr/bin/g++
    args: [ main.cpp, -o, main, -O2, -lm, -std=c++11, -DONLINE_JUDGE ]
  run:
    ratio: 1.0
    cmd: main
- name: Pascal
  suffix: pas
  source: main.pas
  compile:
    time: 10.0
    cmd: /usr/bin/fpc
    args: [ main.pas ]
  run:
    ratio: 1.0
    cmd: main
