port: 7974
host: localhost
concurrent: 2
database: mongodb://127.0.0.1:27017/doj
log: debug
secret: doj_secret
registration: true
mail:
  host: smtp.mailtrap.io
  port: 2525
  auth:
    user: 2e35494e193977
    pass: 1a2a2128eb634e
languages:
- name: C
  suffix: c
- name: C++
  suffix: cpp
- name: Pascal
  suffix: pas
